spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${db.uamdb.ip}:${db.uamdb.port}/plt_uam?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: ${db.uamdb.username}
    password: ${db.uamdb.password}
    druid:
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      query-timeout: 6000
      transaction-query-timeout: 6000
      remove-abandoned-timeout: 1800
      filter-class-names: stat
      filters: stat,config

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dunzung.dcp.uaa.entity

#Swagger
api:
  swagger:
    title: UAA服务
    contact: zhijund@163.com
    version: 1.0
    basePackage: com.dunzung.dcp.uaa.controller

#Admin
info:
  name: dcp-uaa
  description: UAA服务
  version: 1.0.0

